### ISSUE TITLE
Invest Time into Researching User Authentication

### ISSUE THREAD

**Issue by allenzhai** [allenzhai/Psychify#173]

**Comment by ethanbwaite** [comment]
https://medium.com/@yongelee/understanding-user-authentication-in-your-web-app-and-how-to-implement-it-part-1-the-high-level-ab91336ab77c
http://www.passportjs.org/packages/passport-local/

**Comment by allenzhai** [comment]
Estimate 2 Hours

**Comment by allenzhai** [comment]
Actual 1.5 Hours

**Comment by zzheng07** [comment]
Estimate 2 Hours

**Comment by Andrii-I** [comment]
Actual 1 hr
