### ISSUE TITLE
Re-Registering causing an extended blank screen

### ISSUE THREAD

**Issue by zzheng07** [allenzhai/Psychify#207]
Description:
The register page was blank, after I created an account and attempted to log in again. It
appeared to have fully loaded, but there was nothing to see. I would have expected to see
the registration pop up like before, but the page was blank instead.

Reproduction steps:
• I logged in
• I opened a new page
• I hit register
• The page was blank

Expected behavior: 
I expected the registration page to show up or some indication that was already logged in

Observed behavior: 
The page is blank, instead of the registration page

**Comment by Andrii-I** [comment]
Was not able to replicate. Probably fixed after implementation of the account system?

**Comment by Andrii-I** [comment]
Can not reproduce
