### ISSUE TITLE
DSM V Story #1

### ISSUE THREAD

**Issue by cal-brown** [allenzhai/Psychify#24]
As a medical student, I want to browse a list of symptoms by their first letter, so I can easily go to a specific entry.

**Comment by zzheng07** [comment]
Tasks I am proposing,
1. Investment in Learning [React Tutorial] (https://reactjs.org/tutorial/tutorial.html)
2. Investment in Learning How to deploy application over the cloud
3. Set up an application server to host our application
4. Set up a MySQL database server (AWS or Heruko)
5. Set up pipelines to continuously delivery our application from GitHub to server
6. [Front End]Create a landing page.
7. [Front End]Create a listing page with all entries from DSM-V
8. Built APIs for listing entries
9. Built APIs status page.
10. Prepare most popular entries from DSM-V (most popular symptoms, conditions, etc)
