### ISSUE TITLE
Investment in Learning: React

### ISSUE THREAD

**Issue by cal-brown** [allenzhai/Psychify#46]
https://reactjs.org/tutorial/tutorial.html
- [x] @allenzhai 
2/9/20 11:45 AM - 12:00 PM

- [x] @Andrii-I 
- [x] @ethanbwaite 
2/9/20 12:00PM - 4:00PM

- [x] @gaprogg 
- [x] @Hobbes1118  2/9/20 11:00 AM - 12:30 PM (Partial)
- [x] @zzheng07

**Comment by Hobbes1118** [comment]
#24

**Comment by zzheng07** [comment]
Group Estimate = 2 hours

**Comment by Andrii-I** [comment]
Actual time: 3 hrs (2 hrs planned)
