### ISSUE TITLE
Investment in Learning: How to deploy application over cloud

### ISSUE THREAD

**Issue by cal-brown** [allenzhai/Psychify#48]
- [x] @allenzhai 
- [x] @Andrii-I 
- [ ] @ethanbwaite 
- [ ] @gaprogg 
- [ ] @Hobbes1118 
- [ ] @zzheng07

**Comment by Hobbes1118** [comment]
#24

**Comment by zzheng07** [comment]
Group Estimate = 3 hours

**Comment by allenzhai** [comment]
https://www.youtube.com/watch?v=QTOkqzCTGxw

**Comment by allenzhai** [comment]
https://blog.heroku.com/deploying-react-with-zero-configuration

**Comment by allenzhai** [comment]
Actual: 1 1/2 hours

**Comment by Andrii-I** [comment]
Actual time: 1 hr (3 hrs planned)
