### ISSUE TITLE
Investment in Learning: How to build REST API with Express web framework

### ISSUE THREAD

**Issue by cal-brown** [allenzhai/Psychify#49]
- [ ] @allenzhai 
- [x] @Andrii-I 
- [ ] @ethanbwaite 
- [ ] @gaprogg 
- [ ] @Hobbes1118 
- [ ] @zzheng07

**Comment by Hobbes1118** [comment]
#24

**Comment by zzheng07** [comment]
Group Estimate = 3 hours

**Comment by allenzhai** [comment]
https://www.youtube.com/watch?v=L72fhGm1tfE

**Comment by ethanbwaite** [comment]
https://www.youtube.com/watch?v=pKd0Rpw7O48

**Comment by allenzhai** [comment]
Actual: 5 hours

**Comment by Andrii-I** [comment]
Actual time: 2 hrs
