### ISSUE TITLE
Investment in Learning: MySQL Database

### ISSUE THREAD

**Issue by cal-brown** [allenzhai/Psychify#51]
- [x] @allenzhai 
- [x] @Andrii-I 
- [ ] @ethanbwaite 
- [x] @gaprogg 
- [x] @Hobbes1118 
- [x] @zzheng07  2/9/20 8:00PM-10:00PM

**Comment by Hobbes1118** [comment]
#24

**Comment by zzheng07** [comment]
Group Estimate  = 2 hours

**Comment by allenzhai** [comment]
1 hour

**Comment by Andrii-I** [comment]
Actual time: 1 hr (2 hrs planned)
